-- Normalized, auditable food taxonomy for the existing cat and dog catalogues.
-- This migration is intentionally conservative: an absent/ambiguous claim creates
-- a review item instead of a low-confidence searchable tag.

create table if not exists public.food_tags (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug = lower(slug) and slug ~ '^[a-z0-9_]+$'),
  label_ko text not null,
  label_en text not null,
  category text not null check (category in (
    'processing_method', 'preparation_type', 'life_stage',
    'ingredient_condition', 'protein_source', 'product_class', 'management_purpose'
  )),
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category, slug)
);

create table if not exists public.feed_food_tags (
  feed_id uuid not null references public.feeds(id) on delete cascade,
  tag_id bigint not null references public.food_tags(id) on delete restrict,
  source text not null check (source in (
    'existing_field', 'manufacturer_claim', 'ingredient_derived',
    'product_name_derived', 'manual', 'migration'
  )),
  confidence text not null check (confidence in ('high', 'medium')),
  reason text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (feed_id, tag_id)
);

create table if not exists public.dog_feed_food_tags (
  dog_feed_id uuid not null references public.dog_feeds(id) on delete cascade,
  tag_id bigint not null references public.food_tags(id) on delete restrict,
  source text not null check (source in (
    'existing_field', 'manufacturer_claim', 'ingredient_derived',
    'product_name_derived', 'manual', 'migration'
  )),
  confidence text not null check (confidence in ('high', 'medium')),
  reason text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (dog_feed_id, tag_id)
);

create table if not exists public.food_tag_review_queue (
  id bigint generated by default as identity primary key,
  species text not null check (species in ('cat', 'dog')),
  product_id uuid not null,
  issue_type text not null check (issue_type in (
    'unknown_processing_method', 'unknown_life_stage', 'ambiguous_veterinary_diet',
    'ambiguous_chicken_free', 'ambiguous_grain_free', 'unknown_protein_source',
    'conflicting_evidence'
  )),
  reason text not null,
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  unique (species, product_id, issue_type)
);

create index if not exists food_tags_category_active_sort_idx
  on public.food_tags(category, is_active, sort_order, id);
create index if not exists feed_food_tags_tag_feed_idx on public.feed_food_tags(tag_id, feed_id);
create index if not exists dog_feed_food_tags_tag_feed_idx on public.dog_feed_food_tags(tag_id, dog_feed_id);
create index if not exists food_tag_review_queue_open_idx
  on public.food_tag_review_queue(species, issue_type, product_id) where status = 'open';

insert into public.food_tags (slug, label_ko, label_en, category, description, sort_order) values
  ('freeze_dried','동결건조','Freeze-dried','processing_method','동결건조 공정이 명시된 제품',10),
  ('air_dried','에어드라이','Air-dried','processing_method','에어드라이 공정이 명시된 제품',20),
  ('oven_baked','오븐베이크드','Oven-baked','processing_method','오븐 베이킹 공정이 명시된 제품',30),
  ('low_temp_cooked','저온조리','Low-temperature cooked','processing_method','저온 조리가 명시된 제품',40),
  ('extruded','압출','Extruded','processing_method','압출 공정이 명시된 제품(건식이라는 이유만으로 추정하지 않음)',50),
  ('dehydrated','탈수','Dehydrated','processing_method','탈수 공정이 명시된 제품',60),
  ('raw','생식','Raw','preparation_type','제조사가 raw/생식으로 명시한 제품',10),
  ('kitten','키튼','Kitten','life_stage','고양이 성장기',10),
  ('adult_cat','성묘','Adult cat','life_stage','성묘 유지기',20),
  ('senior_cat','노령묘','Senior cat','life_stage','노령묘',30),
  ('all_life_stages_cat','고양이 전연령','All life stages (cat)','life_stage','고양이 전연령',40),
  ('puppy','퍼피','Puppy','life_stage','강아지 성장기',50),
  ('adult_dog','성견','Adult dog','life_stage','성견 유지기',60),
  ('senior_dog','노령견','Senior dog','life_stage','노령견',70),
  ('all_life_stages_dog','강아지 전연령','All life stages (dog)','life_stage','강아지 전연령',80),
  ('grain_free','그레인프리','Grain-free','ingredient_condition','공식 claim 또는 완전한 전성분으로 확인',10),
  ('chicken_free','치킨프리','Chicken-free','ingredient_condition','닭 및 출처 불명 가금류 성분이 없는 공개 전성분으로 확인',20),
  ('single_animal_protein','단일 동물성 단백질','Single animal protein','ingredient_condition','공식 단일 단백질 claim',30),
  ('limited_ingredient','제한 원료','Limited ingredient','ingredient_condition','공식 Limited Ingredient/LID claim',40),
  ('chicken','닭','Chicken','protein_source','주 단백질원',10),
  ('turkey','칠면조','Turkey','protein_source','주 단백질원',20),
  ('duck','오리','Duck','protein_source','주 단백질원',30),
  ('beef','소','Beef','protein_source','주 단백질원',40),
  ('lamb','양','Lamb','protein_source','주 단백질원',50),
  ('pork','돼지','Pork','protein_source','주 단백질원',60),
  ('rabbit','토끼','Rabbit','protein_source','주 단백질원',70),
  ('venison','사슴','Venison','protein_source','주 단백질원',80),
  ('salmon','연어','Salmon','protein_source','주 단백질원',90),
  ('tuna','참치','Tuna','protein_source','주 단백질원',100),
  ('white_fish','흰살생선','White fish','protein_source','주 단백질원',110),
  ('fish','생선','Fish','protein_source','어종이 특정되지 않은 주 단백질원',120),
  ('cod','대구','Cod','protein_source','주 단백질원',130),
  ('pollock','명태','Pollock','protein_source','주 단백질원',140),
  ('trout','송어','Trout','protein_source','주 단백질원',150),
  ('herring','청어','Herring','protein_source','주 단백질원',160),
  ('mackerel','고등어','Mackerel','protein_source','주 단백질원',170),
  ('sardine','정어리','Sardine','protein_source','주 단백질원',180),
  ('anchovy','멸치','Anchovy','protein_source','주 단백질원',190),
  ('quail','메추리','Quail','protein_source','주 단백질원',200),
  ('goat','염소','Goat','protein_source','주 단백질원',210),
  ('horse','말','Horse','protein_source','주 단백질원',220),
  ('kangaroo','캥거루','Kangaroo','protein_source','주 단백질원',230),
  ('bison','바이슨','Bison','protein_source','주 단백질원',240),
  ('wild_boar','멧돼지','Wild boar','protein_source','주 단백질원',250),
  ('egg','계란','Egg','protein_source','메인단백질 필드에 명시된 주 단백질원',260),
  ('insect','곤충','Insect','protein_source','곤충 유래 주 단백질원',270),
  ('complete_food','주식','Complete food','product_class','완전·균형 영양식',10),
  ('complementary_food','보조식','Complementary food','product_class','보완/보조 사료',20),
  ('treat','간식','Treat','product_class','간식',30),
  ('veterinary_diet','수의학적 영양관리식','Veterinary diet','product_class','공식 veterinary/clinical/therapeutic 제품군',40),
  ('urinary','요로','Urinary','management_purpose','요로 영양관리 목적',10),
  ('renal','신장','Renal','management_purpose','신장 영양관리 목적',20),
  ('digestive','소화기','Digestive','management_purpose','소화기 영양관리 목적',30),
  ('skin_allergy','피부·알레르기','Skin & allergy','management_purpose','피부 또는 알레르기 영양관리 목적',40),
  ('weight_management','체중관리','Weight management','management_purpose','체중 영양관리 목적',50),
  ('hepatic','간','Hepatic','management_purpose','간 영양관리 목적',60),
  ('diabetes','당뇨','Diabetes','management_purpose','당뇨 영양관리 목적',70)
on conflict (slug) do update set
  label_ko = excluded.label_ko, label_en = excluded.label_en,
  category = excluded.category, description = excluded.description,
  sort_order = excluded.sort_order, is_active = true, updated_at = now();

-- The function reads known fields through to_jsonb so it remains compatible with
-- catalogue schema additions. Structured fields take precedence over names.
create or replace function public.backfill_food_tags()
returns table(species text, products bigint, tagged_products bigint, untagged_products bigint)
language plpgsql security definer set search_path = public as $$
declare
  r record; j jsonb; blob text; name_text text; ingredients text; protein text;
  class_text text; identity_text text; tag_slug text; tag_source text; tag_reason text;
  has_chicken boolean; has_ambiguous_poultry boolean; has_grain boolean;
  has_ingredients boolean; is_vet_line boolean; has_life_stage boolean;
  has_protein_source boolean; relation_name text;
begin
  delete from public.feed_food_tags where source <> 'manual';
  delete from public.dog_feed_food_tags where source <> 'manual';
  delete from public.food_tag_review_queue where status = 'open';

  for relation_name in select unnest(array['feeds','dog_feeds']) loop
    for r in execute format('select * from public.%I', relation_name) loop
      j := to_jsonb(r);
      name_text := lower(coalesce(j->>'제품명',''));
      ingredients := lower(coalesce(j->>'전성분', j->>'ingredients', ''));
      protein := lower(coalesce(j->>'메인단백질', j->>'main_protein', ''));
      class_text := lower(coalesce(j->>'완전식여부', j->>'product_type', j->>'category', ''));
      identity_text := lower(concat_ws(' ', j->>'제조사', name_text, class_text));
      blob := lower(concat_ws(' ', identity_text, j->>'description', j->>'제품설명'));
      has_ingredients := length(trim(ingredients)) >= 10;
      tag_source := 'product_name_derived'; tag_reason := '제품명/제품군의 명시적 표현';

      -- Explicit processing/preparation claims only; never infer extrusion from dry type.
      foreach tag_slug in array array['freeze_dried','air_dried','oven_baked','low_temp_cooked','extruded','dehydrated','raw'] loop
        if (tag_slug='freeze_dried' and blob ~ '(freeze[ -]?dried|동결 ?건조)') or
           (tag_slug='air_dried' and blob ~ '(air[ -]?dried|에어 ?드라이)') or
           (tag_slug='oven_baked' and blob ~ '(oven[ -]?baked|오븐 ?(베이크|구운))') or
           (tag_slug='low_temp_cooked' and blob ~ '(low[ -]?temp(erature)? cooked|저온 ?(조리|쿠킹))') or
           (tag_slug='extruded' and blob ~ '(extrud(e|ed)|압출)') or
           (tag_slug='dehydrated' and blob ~ '(dehydrat(ed|ed)|탈수)') or
           (tag_slug='raw' and blob ~ '(^|[^a-z])(raw|생식)([^a-z]|$)') then
          execute format('insert into public.%I (%I,tag_id,source,confidence,reason) select $1,id,$2,$3,$4 from food_tags where slug=$5 on conflict do nothing',
            case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
            case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end)
            using r.id, tag_source, 'high', tag_reason, tag_slug;
        end if;
      end loop;

      -- Species-specific life stages. AAFCO/FEDIAF/all-life-stage wording is accepted.
      tag_slug := case
        when relation_name='feeds' and blob ~ '(all life stages|전 ?연령|모든 생애)' then 'all_life_stages_cat'
        when relation_name='feeds' and blob ~ '(kitten|키튼|자묘|성장기)' then 'kitten'
        when relation_name='feeds' and blob ~ '(senior|시니어|노령묘)' then 'senior_cat'
        when relation_name='feeds' and blob ~ '(adult|어덜트|성묘)' then 'adult_cat'
        when relation_name='dog_feeds' and blob ~ '(all life stages|전 ?연령|모든 생애)' then 'all_life_stages_dog'
        when relation_name='dog_feeds' and blob ~ '(puppy|퍼피|자견|성장기)' then 'puppy'
        when relation_name='dog_feeds' and blob ~ '(senior|시니어|노령견)' then 'senior_dog'
        when relation_name='dog_feeds' and blob ~ '(adult|어덜트|성견)' then 'adult_dog' end;
      has_life_stage := tag_slug is not null;
      if has_life_stage then
        execute format('insert into public.%I (%I,tag_id,source,confidence,reason) select $1,id,$2,$3,$4 from food_tags where slug=$5 on conflict do nothing',
          case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
          case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end)
          using r.id, 'product_name_derived', 'medium', '제품명/설명의 명시적 생애주기', tag_slug;
      end if;

      -- Existing main-protein is authoritative and may yield multiple tags.
      has_protein_source := false;
      foreach tag_slug in array array[
        'chicken','turkey','duck','beef','lamb','pork','rabbit','venison','salmon','tuna',
        'white_fish','cod','pollock','trout','herring','mackerel','sardine','anchovy','fish',
        'quail','goat','horse','kangaroo','bison','wild_boar','egg','insect'
      ] loop
        if (tag_slug='chicken' and protein ~ '(chicken|닭|치킨|계육)') or
           (tag_slug='turkey' and protein ~ '(turkey|칠면조)') or
           (tag_slug='duck' and protein ~ '(duck|오리)') or
           (tag_slug='beef' and protein ~ '(beef|소고기|쇠고기|우육)') or
           (tag_slug='lamb' and protein ~ '(lamb|양고기|양육)') or
           (tag_slug='pork' and protein ~ '(pork|돼지|돈육)') or
           (tag_slug='rabbit' and protein ~ '(rabbit|토끼)') or
           (tag_slug='venison' and protein ~ '(venison|사슴)') or
           (tag_slug='salmon' and protein ~ '(salmon|연어)') or
           (tag_slug='tuna' and protein ~ '(tuna|참치)') or
           (tag_slug='white_fish' and protein ~ '(white ?fish|흰살 ?생선|백색어)') or
           (tag_slug='cod' and protein ~ '(cod|대구)') or
           (tag_slug='pollock' and protein ~ '(pollock|명태|황태)') or
           (tag_slug='trout' and protein ~ '(trout|송어)') or
           (tag_slug='herring' and protein ~ '(herring|청어)') or
           (tag_slug='mackerel' and protein ~ '(mackerel|고등어)') or
           (tag_slug='sardine' and protein ~ '(sardine|정어리)') or
           (tag_slug='anchovy' and protein ~ '(anchovy|멸치)') or
           (tag_slug='quail' and protein ~ '(quail|메추리)') or
           (tag_slug='goat' and protein ~ '(goat|염소)') or
           (tag_slug='horse' and protein ~ '(horse|말고기|마육)') or
           (tag_slug='kangaroo' and protein ~ '(kangaroo|캥거루)') or
           (tag_slug='bison' and protein ~ '(bison|바이슨|들소)') or
           (tag_slug='wild_boar' and protein ~ '(wild ?boar|멧돼지)') or
           (tag_slug='egg' and protein ~ '(egg|계란|달걀|난백|전란)') or
           (tag_slug='insect' and protein ~ '(insect|곤충|밀웜|동애등에)') or
           (tag_slug='fish' and protein ~ '(fish|생선|어류)' and protein !~ '(salmon|연어|tuna|참치|white ?fish|흰살|백색어|cod|대구|pollock|명태|황태|trout|송어|herring|청어|mackerel|고등어|sardine|정어리|anchovy|멸치)') then
          has_protein_source := true;
          execute format('insert into public.%I (%I,tag_id,source,confidence,reason) select $1,id,$2,$3,$4 from food_tags where slug=$5 on conflict do nothing',
            case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
            case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end)
            using r.id, 'existing_field', 'high', '메인단백질 필드의 정규화 매핑', tag_slug;
        end if;
      end loop;
      execute format(
        'select exists (select 1 from public.%I x join public.food_tags t on t.id=x.tag_id where x.%I=$1 and t.category=''protein_source'')',
        case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
        case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end
      ) into has_protein_source using r.id;

      -- Product class. Veterinary status needs an official product-line signal.
      tag_slug := case when class_text ~ '(완전|주식|complete)' then 'complete_food'
                       when class_text ~ '(보조|보완|complement)' then 'complementary_food'
                       when class_text ~ '(간식|treat|snack)' then 'treat' end;
      if tag_slug is not null then
        execute format('insert into public.%I (%I,tag_id,source,confidence,reason) select $1,id,$2,$3,$4 from food_tags where slug=$5 on conflict do nothing',
          case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
          case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end)
          using r.id, 'existing_field', 'high', '완전식여부/제품 분류 필드', tag_slug;
      end if;
      is_vet_line :=
        (
          identity_text ~ '(royal canin|로얄캐닌)' and
          identity_text ~ '(veterinary|vet ?diet|벳 ?다이어트|s ?/ ?o|early ?renal|renal|gastro ?intestinal|gastrointestinal|hepatic|satiety|anallergenic|가스트로 ?인테스티널|세타이어티|아날러제닉|헤파틱|레날)' and
          identity_text !~ '(urinary ?care|digestive ?care|light ?weight ?care)'
        ) or
        identity_text ~ '(hill''?s|힐스).*(prescription diet|프리 ?스크립션( ?다이어트)?)' or
        identity_text ~ '(farmina|파미나).*(vet ?life|벳 ?라이프)' or
        identity_text ~ '(monge|몬지).*(vetsolution|vet ?solution|벳 ?솔루션|벳솔루션)' or
        identity_text ~ '(v[.]?o[.]?m|브이오엠).*(rx|알엑스)';
      if is_vet_line then
        execute format('insert into public.%I (%I,tag_id,source,confidence,reason) select $1,id,$2,$3,$4 from food_tags where slug=''veterinary_diet'' on conflict do nothing',
          case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
          case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end)
          using r.id, 'manufacturer_claim', 'high', '제조사·제품명에서 확인된 공식 수의학적 영양관리 제품군';
      end if;

      foreach tag_slug in array array['urinary','renal','digestive','skin_allergy','weight_management','hepatic','diabetes'] loop
        if (tag_slug='urinary' and blob ~ '(urinary|요로|비뇨|struvite|스트루바이트|유리너리|유러너리)') or
           (tag_slug='renal' and blob ~ '(renal|kidney|신장|레날)') or
           (tag_slug='digestive' and blob ~ '(digestive|gastro|소화기|장 건강|가스트로 ?인테스티널)') or
           (tag_slug='skin_allergy' and blob ~ '(skin|derma|allerg|피부|알레르|아날러제닉|하이포알러제닉)') or
           (tag_slug='weight_management' and blob ~ '(weight (management|control)|satiety|체중 ?(관리|조절)|세타이어티)') or
           (tag_slug='hepatic' and blob ~ '(hepatic|liver|간 건강|간질환|헤파틱)') or
           (tag_slug='diabetes' and blob ~ '(diabet(es|ic)|당뇨|다이아베틱)') then
          execute format('insert into public.%I (%I,tag_id,source,confidence,reason) select $1,id,$2,$3,$4 from food_tags where slug=$5 on conflict do nothing',
            case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
            case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end)
            using r.id, 'manufacturer_claim', 'high', '제품명/공식 제품군에 명시된 관리 목적', tag_slug;
        end if;
      end loop;

      -- Ingredient-condition claims. Grain-free/LID/SAP require explicit claims.
      foreach tag_slug in array array['grain_free','single_animal_protein','limited_ingredient'] loop
        if (tag_slug='grain_free' and blob ~ '(grain[ -]?free|그레인 ?프리|곡물 ?무첨가)') or
           (tag_slug='single_animal_protein' and blob ~ '(single (animal )?protein|단일 (동물성 )?단백질|모노프로틴)') or
           (tag_slug='limited_ingredient' and blob ~ '(limited ingredient|(^|[^a-z])lid([^a-z]|$)|제한 ?원료)') then
          execute format('insert into public.%I (%I,tag_id,source,confidence,reason) select $1,id,$2,$3,$4 from food_tags where slug=$5 on conflict do nothing',
            case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
            case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end)
            using r.id, 'manufacturer_claim', 'high', '제조사 명시 claim', tag_slug;
        end if;
      end loop;

      -- Chicken-free is derived only from a disclosed list with neither chicken nor
      -- an unspecified poultry/animal ingredient. This is not a cross-contact claim.
      has_chicken := ingredients ~ '(chicken|닭|치킨|계육|egg|계란|달걀|난백|전란)';
      has_ambiguous_poultry := ingredients ~ '(poultry|가금(류|육|육분)?|조류|animal fat|animal protein|animal ?by[ -]?products?|animal derivatives|meat and animal derivatives|동물성 ?(지방|단백|부산물)|육류 및 동물성 부산물)';
      if has_ingredients and not has_chicken and not has_ambiguous_poultry then
        execute format('insert into public.%I (%I,tag_id,source,confidence,reason) select $1,id,$2,$3,$4 from food_tags where slug=''chicken_free'' on conflict do nothing',
          case when relation_name='feeds' then 'feed_food_tags' else 'dog_feed_food_tags' end,
          case when relation_name='feeds' then 'feed_id' else 'dog_feed_id' end)
          using r.id, 'ingredient_derived', 'medium', '공개 전성분에 닭·난류 및 출처 불명 가금/동물성 원료가 없음';
      end if;

      -- Review gaps rather than inventing tags.
      if not (blob ~ '(freeze[ -]?dried|동결 ?건조|air[ -]?dried|에어 ?드라이|oven[ -]?baked|오븐 ?(베이크|구운)|low[ -]?temp|저온 ?(조리|쿠킹)|extrud|압출|dehydrat|탈수)') then
        insert into food_tag_review_queue(species,product_id,issue_type,reason,evidence) values
          (case when relation_name='feeds' then 'cat' else 'dog' end,r.id,'unknown_processing_method','명시적 가공 방식 근거 없음',jsonb_build_object('name',name_text)) on conflict do nothing;
      end if;
      if not has_life_stage then
        insert into food_tag_review_queue(species,product_id,issue_type,reason,evidence) values
          (case when relation_name='feeds' then 'cat' else 'dog' end,r.id,'unknown_life_stage','생애주기 근거 없음',jsonb_build_object('name',name_text)) on conflict do nothing;
      end if;
      if not has_protein_source then
        insert into food_tag_review_queue(species,product_id,issue_type,reason,evidence) values
          (case when relation_name='feeds' then 'cat' else 'dog' end,r.id,'unknown_protein_source',
           case when length(trim(protein))=0 then '메인단백질 필드가 비어 있음' else '메인단백질 값에 대응하는 protein_source taxonomy가 없음' end,
           jsonb_build_object('main_protein',nullif(protein,''),'ingredients_present',has_ingredients)) on conflict do nothing;
      end if;
      if has_ambiguous_poultry and not has_chicken then
        insert into food_tag_review_queue(species,product_id,issue_type,reason,evidence) values
          (case when relation_name='feeds' then 'cat' else 'dog' end,r.id,'ambiguous_chicken_free','출처 불명 poultry/animal 성분 때문에 자동 판정 제외',jsonb_build_object('ingredients',ingredients)) on conflict do nothing;
      end if;
      has_grain := ingredients ~ '(wheat|corn|maize|rice|barley|oat|rye|millet|sorghum|밀|옥수수|쌀|보리|귀리|호밀|수수)';
      if has_ingredients and not has_grain and blob !~ '(grain[ -]?free|그레인 ?프리|곡물 ?무첨가)' then
        insert into food_tag_review_queue(species,product_id,issue_type,reason,evidence) values
          (case when relation_name='feeds' then 'cat' else 'dog' end,r.id,'ambiguous_grain_free','공식 claim이 없고 전성분 완전성 확인이 불가하여 자동 판정 제외',jsonb_build_object('ingredients',ingredients)) on conflict do nothing;
      end if;
      if identity_text ~ '(vet|veterinary|prescription|clinical|therapeutic|동물병원|처방|벳|rx)' and not is_vet_line then
        insert into food_tag_review_queue(species,product_id,issue_type,reason,evidence) values
          (case when relation_name='feeds' then 'cat' else 'dog' end,r.id,'ambiguous_veterinary_diet','수의학 관련 표현은 있으나 공식 제품군 근거 부족',jsonb_build_object('name',name_text,'brand',j->>'제조사')) on conflict do nothing;
      end if;
    end loop;
  end loop;

  return query
    select 'cat', count(*)::bigint, count(*) filter(where exists(select 1 from feed_food_tags x where x.feed_id=f.id))::bigint,
           count(*) filter(where not exists(select 1 from feed_food_tags x where x.feed_id=f.id))::bigint from feeds f
    union all
    select 'dog', count(*)::bigint, count(*) filter(where exists(select 1 from dog_feed_food_tags x where x.dog_feed_id=f.id))::bigint,
           count(*) filter(where not exists(select 1 from dog_feed_food_tags x where x.dog_feed_id=f.id))::bigint from dog_feeds f;
end $$;

select * from public.backfill_food_tags();

-- Read-only validation/query surface. The category array supports AND across axes
-- without adding denormalized columns to either product table.
create or replace view public.food_tag_distribution as
select 'cat'::text species, t.category, t.slug, t.label_ko, count(*)::bigint product_count
from public.feed_food_tags x join public.food_tags t on t.id=x.tag_id group by t.category,t.slug,t.label_ko
union all
select 'dog', t.category, t.slug, t.label_ko, count(*)::bigint
from public.dog_feed_food_tags x join public.food_tags t on t.id=x.tag_id group by t.category,t.slug,t.label_ko;

alter table public.food_tags enable row level security;
alter table public.feed_food_tags enable row level security;
alter table public.dog_feed_food_tags enable row level security;
alter table public.food_tag_review_queue enable row level security;
create policy "active food tags are publicly readable" on public.food_tags for select using (is_active);
create policy "cat food tag relations are publicly readable" on public.feed_food_tags for select using (true);
create policy "dog food tag relations are publicly readable" on public.dog_feed_food_tags for select using (true);
-- No public review-queue policy: it can contain full ingredient evidence.

grant select on public.food_tags, public.feed_food_tags, public.dog_feed_food_tags, public.food_tag_distribution to anon, authenticated;
revoke all on public.food_tag_review_queue from anon, authenticated;
revoke execute on function public.backfill_food_tags() from public, anon, authenticated;

comment on table public.food_tags is 'Canonical searchable food-tag taxonomy; one tag belongs to one search axis.';
comment on table public.feed_food_tags is 'Audited many-to-many tags for cat feeds.';
comment on table public.dog_feed_food_tags is 'Audited many-to-many tags for dog feeds.';
comment on table public.food_tag_review_queue is 'Products deliberately left untagged for an ambiguous axis, for staff review.';
